name: flutter_qr_barcode_scanner
description: A Flutter app for scanning QR codes and barcodes.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner_plus: ^2.0.12
  permission_handler: ^11.3.1
  camera: ^0.10.5+9
  # Enhanced features
  shared_preferences: ^2.2.3
  sqflite: ^2.3.0
  path: ^1.8.3
  url_launcher: ^6.2.1
  qr_flutter: ^4.1.0
  # Animations and UI
  lottie: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  # Feedback
  vibration: ^1.8.4
  audioplayers: ^5.2.1
  # Utils
  intl: ^0.19.0
  share_plus: ^7.2.2
  file_picker: ^6.1.1
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic